# Generated by Django 3.1.7 on 2023-10-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_authentication', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activesession',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
