// import DescriptionBox from "examples/DescriptionBox";
import SuiBox from "components/SuiBox";
import SuiTypography from "components/SuiTypography";

function Authentication() {
  return (
    <SuiBox pl={4} pt={2}>
      <SuiTypography variant="h3" py={1} id="authentication">
        Authentication
      </SuiTypography>
      <SuiTypography variant="body2" py={1}>
        Data API Connect uses Access Token and is required for every API request. The token has an
        expiration records and the developer is responsible for generating a new token when the
        current token expires. Token Authentication can only be used over HTTPS (SSL).
      </SuiTypography>
      <SuiTypography variant="body2" py={1}>
        Access Token (also called token authentication) is an HTTP authentication scheme that
        involves security tokens. The Access Token is a cryptic string, generated by the server in
        response to a login request. The client must send this token in the Authorization header
        when making requests to protected resources:
      </SuiTypography>
      <SuiTypography variant="body2" py={1}>
        <strong>Please note:</strong>&nbsp;You can get your Access Token in your dashboard.
      </SuiTypography>
    </SuiBox>
  );
}

export default Authentication;
