# Generated by Django 3.2.13 on 2023-09-04 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='api_key',
            field=models.EmailField(db_index=True, default='9b212709a28eac924b262a2fd6fdb66cd0f3ec6c7ef587e90e36dfdfbe97959b', max_length=254, unique=True),
        ),
    ]
