# Generated by Django 3.2.13 on 2023-09-04 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0004_user_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.EmailField(db_index=True, default='0516cb4abbed3d103d3ef1ae86d196f340e290a98a830fee22d54bf8cd6ba0e3', max_length=254, unique=True),
        ),
    ]
