# Generated by Django 3.2.13 on 2023-09-04 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0005_alter_user_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(db_index=True, default='051f1def76a56a69bb2c5a62a6427aba06e6e282245a631fd621c77d170488c4', max_length=255, unique=True),
        ),
    ]
