# Generated by Django 3.2.13 on 2023-09-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0006_alter_user_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(db_index=True, default='321c8663e8e4197325f889cd6eac92217fcab7d2dbe097dc442604289c2cad5c', max_length=255, unique=True),
        ),
    ]
