# Generated by Django 3.2.13 on 2023-09-04 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0007_alter_user_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(db_index=True, default='5382db9a1e661c3400083eaf0defdebd90d9476439e69560779ef06e0f473249', max_length=255, unique=True),
        ),
    ]
