# Generated by Django 3.2.13 on 2023-09-04 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0009_alter_user_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(db_index=True, default='6971b3de12580d3162425460d53ef0803ed3026e6eca24391c17f9151a1528c6', max_length=255, unique=True),
        ),
    ]
