# Generated by Django 3.2.13 on 2023-09-04 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0011_alter_user_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(db_index=True, default='77f0ca2139799d3e9aa636354001b6f3bcc503c0aef737ad6bbb635ce2f719d4', max_length=255, unique=True),
        ),
    ]
