# Generated by Django 3.2.13 on 2023-09-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0012_alter_user_api_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(db_index=True, default='b568b8a01d2374e8d1f4e96f2b6b0ae78d2ff7cf161dd8320274933acae9b4c2', max_length=255, unique=True),
        ),
    ]
