# Generated by Django 3.2.13 on 2023-09-04 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0013_alter_user_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(default='primary', max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='api_key',
            field=models.CharField(db_index=True, default='184af2e493bee17dffb31ae711decbdcf32e06db779b503ec2c747e753bf0438', max_length=255, unique=True),
        ),
    ]
