# Generated by Django 3.2.8 on 2023-09-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0015_auto_20230904_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='plan',
            field=models.CharField(default='free', max_length=30),
        ),
    ]
