# Generated by Django 3.1.7 on 2023-10-12 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0017_user_is_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
