import {
  Home,
  SignIn,
  SignUp,
  OTP,
  ForgotPassword,
  ResetPassword,
  Price,
  API,
  Compliance,
  Transparency,
  DataLake,
  Points,
  Terms,
  Contact,
  Usecase,
  Privacy,
} from "@/pages";
import { Dashboard } from "@/layouts";
import {
  HomeIcon,
  CurrencyDollarIcon,
  ChartBarIcon,
  ArrowRightOnRectangleIcon,
  ArrowLeftOnRectangleIcon,
  UserPlusIcon,
  ShieldCheckIcon,
  PresentationChartBarIcon,
  DocumentTextIcon,
  UserCircleIcon,
} from "@heroicons/react/24/solid";
import SignOut from "./pages/auth/sign-out";

const routes = [
  {
    type: "none",
    name: "Home",
    key: "home",
    icon: HomeIcon,
    route: "/home",
    element: <Home />,
    authenticated: false,
  },
  {
    type: "none",
    name: "Dashboard",
    key: "dashboard",
    route: "/dashboard",
    icon: PresentationChartBarIcon,
    element: <Dashboard path="main" />,
    authenticated: true,
  },
  {
    type: "collapse",
    name: "Data Viewer",
    key: "tables",
    route: "/dataviewer",
    icon: DocumentTextIcon,
    element: <Dashboard path="dataviewer" />,
    authenticated: true,
  },
  {
    type: "collapse",
    name: "Billing",
    key: "billing",
    route: "/billing",
    icon: CurrencyDollarIcon,
    element: <Dashboard path="billing" />,
    authenticated: true,
  },
  {
    type: "collapse",
    name: "Profile",
    key: "profile",
    route: "/profile",
    icon: UserCircleIcon,
    element: <Dashboard path="profile" />,
    authenticated: true,
  },

  {
    type: "none",
    name: "OTP",
    key: "otp",
    icon: HomeIcon,
    route: "/authentication/email_verify/:id",
    element: <OTP />,
    authenticated: false,
  },
  {
    type: "none",
    name: "Forgot_Password",
    key: "forgotpassword",
    icon: HomeIcon,
    route: "/forgotpassword",
    element: <ForgotPassword />,
    authenticated: false,
  },
  {
    type: "none",
    name: "Reset_Password",
    key: "resetpassword",
    icon: HomeIcon,
    route: "/resetpassword/:id",
    element: <ResetPassword />,
    authenticated: false,
  },
  {
    type: "none",
    name: "Data Lake",
    key: "data_lake",
    route: "/data_lake",
    icon: HomeIcon,
    element: <DataLake />,
    authenticated: false,
  },
  {
    type: "none",
    name: "Datapoints",
    key: "datapoints",
    route: "/data_points",
    element: <Points />,
    icon: HomeIcon,
    authenticated: false,
  },
  {
    type: "none",
    name: "Data Transparency",
    key: "data_transparency",
    route: "/data_transparency",
    element: <Transparency />,
    icon: HomeIcon,
    authenticated: false,
  },
  {
    type: "collapse",
    name: "API",
    key: "api",
    route: "/api",
    icon: ChartBarIcon,
    element: <API />,
    authenticated: false,
  },
  {
    type: "collapse",
    name: "Pricing",
    key: "pricing",
    route: "/pricing",
    icon: CurrencyDollarIcon,
    element: <Price />,
    authenticated: false,
  },
  {
    type: "collapse",
    name: "Data Compliance",
    key: "data_compliance",
    route: "/data-compliance",
    icon: ShieldCheckIcon,
    element: <Compliance />,
    authenticated: false,
  },
  {
    type: "collapse",
    name: "Sign In",
    key: "sign-in",
    route: "/authentication/sign-in",
    icon: ArrowRightOnRectangleIcon,
    element: <SignIn />,
    authenticated: false,
  },
  {
    type: "collapse",
    name: "Sign Up",
    key: "sign-up",
    route: "/authentication/sign-up",
    icon: UserPlusIcon,
    element: <SignUp />,
    authenticated: false,
  },
  {
    type: "collapse",
    name: "Logout",
    key: "sign-out",
    route: "/authentication/sign-out",
    icon: ArrowLeftOnRectangleIcon,
    element: <SignOut />,
    authenticated: true,
  },
  {
    type: "none",
    name: "ContactUs",
    key: "contact_us",
    route: "/contact",
    icon: HomeIcon,
    element: <Contact />,
    authenticated: false,
  },
  {
    type: "none",
    name: "Terms",
    key: "terms",
    route: "/terms",
    icon: HomeIcon,
    element: <Terms />,
    authenticated: false,
  },
  {
    type: "none",
    name: "Privacy",
    key: "privacy",
    route: "/privacy",
    icon: HomeIcon,
    element: <Privacy />,
    authenticated: false,
  },
  {
    type: "none",
    name: "Use Case",
    key: "usecase",
    route: "/usecase",
    icon: HomeIcon,
    element: <Usecase />,
    authenticated: false,
  },
];

export default routes;
